name: Tag repository

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (e.g. v0.0.1)'
        required: true
        # default: 'warning'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.tag }}',
              sha: context.sha
            })
