name: Publish TAG to quay.io

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be published to quay.io'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string


jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for progressive mode to work
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
      - name: Prepare Python project
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-builder
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml
      - name: Execute Ansible Builder
        run: |
          ansible-builder build --tag awx-ee-openstack:${{ github.event.inputs.tag }} --tag awx-ee-openstack:latest
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io/trikorasolns
          image: awx-ee-openstack
          tags: "${{ github.event.inputs.tag }} latest"
          username: ${{ secrets.QUAY_IO_USER }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
