name: Release

on:
  push:
    tags:
      - '*'

jobs:
  call-workflow-passing-data:
    uses: trikorasolns/awx-ee-openstack/.github/workflows/publish.yaml@main
    with:
      tag: "${{ github.ref }}"
